import {Miniflare} from 'miniflare';
import {readFile,readdir} from 'node:fs/promises';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {randomUUID} from 'node:crypto';
async function walk(dir){let rows=[];for(const ent of await readdir(dir,{withFileTypes:true})){const p=resolve(dir,ent.name);if(ent.isDirectory())rows.push(...await walk(p));else if(p.endsWith('.js'))rows.push({type:'ESModule',path:p});}return rows}
const all=await walk('dist/server');all.sort((a,b)=>(a.path===resolve('dist/server/index.js')?-1:b.path===resolve('dist/server/index.js')?1:0));
const entry=all.find(x=>x.path===resolve('dist/server/index.js'));entry.contents="const RealDate=Date;globalThis.Date=class extends RealDate{constructor(...args){super(...(args.length?args:['2026-09-30T16:00:00Z']))}static now(){return new RealDate('2026-09-30T16:00:00Z').valueOf()}};\n"+await readFile(entry.path,'utf8');
const mf=new Miniflare({modules:all,modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'test-finance'},port:0});
let checks=0;try{await mf.ready;const db=await mf.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort()){const sql=await readFile('drizzle/'+file,'utf8');for(const stmt of sql.split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(stmt).run();}
async function request(user,body,origin){const headers={'Content-Type':'application/json'};if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=user+'@example.test'}if(origin)headers.origin=origin;const r=await mf.dispatchFetch('https://app.test/api/finance',{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});const text=await r.text();if(!text)throw new Error(`Empty response status ${r.status} ${r.headers.get("location")}`);return {status:r.status,data:JSON.parse(text)}}
function check(value,msg){assert.ok(value,msg);checks++;}
const create=(record,key=randomUUID())=>({action:'create',key,record});
check((await request(null)).status===401,'anonymous read blocked');check((await request(null,create({type:'account',name:'x',initial:0}))).status===401,'anonymous write blocked');check((await request('A',create({type:'account',name:'x',initial:0}),'https://evil.test')).status===403,'cross origin blocked');
const key=randomUUID();let r=await request('A',create({type:'account',name:'Principal',initial:100000},key));check(r.status===200,'account create');const a=r.data.items[0].id;check((await request('B')).data.items.length===0,'owner isolation');r=await request('A',create({type:'account',name:'Principal',initial:100000},key));check(r.data.items.length===1,'replay does not duplicate');check((await request('A',create({type:'account',name:'Changed',initial:100000},key))).status===400,'key mismatch rejected');check((await request('B',create({type:'transaction',name:'Unauthorized',amount:1,date:'2026-09-30',accountId:a,kind:'expense',category:'Outros',status:'posted'}))).status===400,'foreign account rejected');check((await request('A',create({type:'account',name:'Bad',initial:0.1}))).status===400,'fractional cents rejected');check((await request('A',create({type:'transaction',name:'Bad date',amount:1,date:'2026-02-31',accountId:a,kind:'expense',category:'Outros',status:'posted'}))).status===400,'invalid date rejected');
r=await request('A',create({type:'account',name:'Reserva',initial:0}));const b=r.data.items.find(x=>x.name==='Reserva').id;check((await request('A',create({type:'transaction',name:'Transfer',amount:10000,date:'2026-09-30',accountId:a,destinationId:b,kind:'transfer',category:'Outros',status:'posted'}))).status===200,'valid transfer');check((await request('A',{action:'delete',key:randomUUID(),id:a})).status===400,'referenced account deletion blocked');
r=await request('A',create({type:'goal',name:'Objetivo',target:20000,current:0,deadline:'2027-01-01'}));const goal=r.data.items.find(x=>x.type==='goal').id;const contribution={action:'contribute',key:randomUUID(),id:goal,amount:10000};await request('A',contribution);r=await request('A',contribution);check(r.data.items.find(x=>x.id===goal).current===10000,'contribution replay idempotent');
await request('A',create({type:'budget',category:'Alimentação',amount:10000,month:'2026-09'}));check((await request('A',create({type:'budget',category:'Alimentação',amount:20000,month:'2026-09'}))).status===400,'duplicate category budget blocked');
r=await request('A',create({type:'card',name:'Cartão',limit:100000,closing:25,due:5}));const card=r.data.items.find(x=>x.type==='card').id;r=await request('A',create({type:'purchase',name:'Compra',amount:10001,date:'2026-09-26',cardId:card,category:'Compras',installments:3}));const installments=r.data.items.filter(x=>x.type==='purchase');check(installments.reduce((s,x)=>s+x.amount,0)===10001,'installments exact');check(installments.map(x=>x.month).sort()[0]==='2026-11','after closing due month correct');
r=await request('A',create({type:'debt',name:'Dívida',amount:5000,deadline:'2027-01-01',rate:''}));const debt=r.data.items.find(x=>x.type==='debt').id;const payment={action:'pay_debt',key:randomUUID(),id:debt,amount:2000,accountId:a,date:'2026-09-30'};r=await request('A',payment);check(r.data.items.find(x=>x.id===debt).amount===3000,'debt reduction');r=await request('A',payment);check(r.data.items.find(x=>x.id===debt).amount===3000,'debt payment replay');check(r.data.items.filter(x=>x.name==='Pagamento · Dívida').length===1,'debt debit atomic and unique');
r=await request('A',{action:'update',key:randomUUID(),id:goal,record:{type:'goal',name:'Objetivo atualizado',target:30000,current:10000,deadline:'2027-01-01'}});check(r.status===200&&r.data.items.find(x=>x.id===goal).target===30000,'goal edit preserves id');check((await request('B',{action:'update',key:randomUUID(),id:goal,record:{type:'goal',name:'Unauthorized',target:1,current:0,deadline:'2027-01-01'}})).status===400,'foreign update blocked');const debtTx=r.data.items.find(x=>x.name==='Pagamento · Dívida');check((await request('A',{action:'delete',key:randomUUID(),id:debtTx.id})).status===400,'linked debt payment protected');check((await request('A',{action:'pay_debt',key:randomUUID(),id:debt,amount:1,accountId:a,date:'2099-01-01'})).status===400,'future debt payment blocked');
r=await request('A',create({type:'transaction',name:'Future expense',amount:1,date:'2099-01-01',accountId:a,kind:'expense',category:'Outros',status:'posted'}));const future=r.data.items.find(x=>x.name==='Future expense');check(future.status==='planned','future posted coerced to planned');check((await request('A',{action:'settle',key:randomUUID(),id:future.id})).status===400,'early confirmation blocked');

// Expanded v2 behaviors: real events, daily reward caps, import, recurring, investment ledger.
let before=await request('A');const initialRecordRewards=before.data.rewards.filter(x=>x.code==='habit_record').length;
await request('A',create({type:'transaction',name:'Another real expense',amount:100,date:'2026-09-30',accountId:a,kind:'expense',category:'Outros',status:'posted'}));r=await request('A');check(r.data.rewards.filter(x=>x.code==='habit_record').length===initialRecordRewards,'daily record XP capped');
const reviewKey=randomUUID();r=await request('A',{action:'review_budget',key:reviewKey});check(r.status===200&&r.data.rewards.some(x=>x.code==='habit_review_budget'),'budget review persists reward');const rewardCount=r.data.rewards.length;r=await request('A',{action:'review_budget',key:randomUUID()});check(r.data.rewards.length===rewardCount,'repeat review does not farm XP');check((await request('A',{action:'review_budget',key:randomUUID(),month:'2020-01'})).status===400,'wrong month review rejected');
const contributionCount=r.data.items.filter(x=>x.type==='contribution').length;check(contributionCount===1,'contribution history persisted');r=await request('A',{action:'withdraw_contribution',key:randomUUID(),id:goal,amount:1000});check(r.data.items.find(x=>x.id===goal).current===9000,'withdraw updates allocation');check(r.data.items.some(x=>x.type==='contribution'&&x.kind==='withdrawal'&&x.amount===1000),'withdraw history persisted');
const imported={action:'import',key:randomUUID(),accountId:a,format:'csv',rows:[{name:'Imported receipt',amount:1234,date:'2026-09-30',kind:'income',category:'Salário',externalId:'ext-001'}]};r=await request('A',imported);check(r.status===200,'import accepted');const importedRow=r.data.items.find(x=>x.externalId==='ext-001');check(importedRow.source==='csv'&&!!importedRow.fingerprint,'import provenance persisted');check((await request('A',{...imported,key:randomUUID()})).status===400,'duplicate import rejected');r=await request('A',{action:'update',key:randomUUID(),id:importedRow.id,record:{type:'transaction',name:'Edited description',amount:1234,date:'2026-09-30',kind:'income',category:'Salário',status:'posted',accountId:a}});check(r.data.items.find(x=>x.id===importedRow.id).fingerprint===importedRow.fingerprint,'import fingerprint survives edit');check((await request('A',{...imported,key:randomUUID()})).status===400,'edited imports remain deduplicated');
r=await request('A',create({type:'recurring',name:'Monthly recurring',amount:100,date:'2026-09-30',kind:'expense',category:'Assinaturas',accountId:a}));const recurring=r.data.items.find(x=>x.type==='recurring').id;r=await request('A',{action:'confirm_recurring',key:randomUUID(),id:recurring,date:'2026-09-30'});check(r.status===200&&r.data.items.some(x=>x.recurringId===recurring),'recurring occurrence confirmed');check((await request('A',{action:'confirm_recurring',key:randomUUID(),id:recurring,date:'2026-09-30'})).status===400,'duplicate occurrence blocked');check((await request('A',{action:'confirm_recurring',key:randomUUID(),id:recurring,date:'2026-09-29'})).status===400,'unaligned occurrence rejected');
r=await request('A',create({type:'investment',name:'Manual asset',quantity:'1',cost:10000,value:10000,category:'Investimentos'}));const asset=r.data.items.find(x=>x.type==='investment').id;
r=await request('A',{action:'trade',key:randomUUID(),id:asset,accountId:a,kind:'buy',quantity:'0.5',amount:5000,fee:10,date:'2026-09-30'});check(r.status===200,'buy accepted');let position=r.data.items.find(x=>x.id===asset);check(position.quantity==='1.5'&&position.cost===15010&&position.value===15000,'buy tracks exact quantity/cost/value');check(r.data.items.some(x=>x.kind==='investment_buy'&&x.amount===5010),'buy cash movement includes fee');
r=await request('A',{action:'trade',key:randomUUID(),id:asset,accountId:a,kind:'sell',quantity:'0.25',amount:3000,fee:5,date:'2026-09-30'});position=r.data.items.find(x=>x.id===asset);check(position.quantity==='1.25'&&position.cost===12508&&position.value===12500,'sale proportionally reduces cost/value');check(r.data.items.some(x=>x.kind==='investment_sell'&&x.amount===2995),'sale cash movement net of fees');check((await request('A',{action:'trade',key:randomUUID(),id:asset,accountId:a,kind:'sell',quantity:'2',amount:1,fee:0,date:'2026-09-30'})).status===400,'oversell blocked');
r=await request('A',{action:'trade',key:randomUUID(),id:asset,accountId:a,kind:'income',quantity:'0',amount:200,fee:2,date:'2026-09-30'});check(r.data.items.find(x=>x.id===asset).quantity==='1.25','dividends do not change quantity');check(r.data.items.some(x=>x.kind==='investment_income'&&x.amount===198),'dividend cash recorded');check((await request('A',{action:'update',key:randomUUID(),id:asset,record:{type:'investment',name:'x',quantity:'10',cost:1,value:1,category:'Investimentos'}})).status===400,'position history cannot be overwritten');
r=await request('A',{action:'review_investments',key:randomUUID()});check(r.data.rewards.some(x=>x.code==='first_investment_review'),'review achievement earned');check(!r.data.rewards.some(x=>x.code==='habit_trade'),'investment size does not earn XP');
r=await request('A',{action:'reconcile',key:randomUUID(),id:a,balance:777777,date:'2026-09-30'});check(r.status===200&&r.data.items.some(x=>x.source==='reconcile'),'reconciliation recorded');check((await request('A',{action:'reconcile',key:randomUUID(),id:a,balance:777777,date:'2026-09-30'})).status===400,'same balance reconciliation blocked');
r=await request('A',{action:'preferences',key:randomUUID(),weeklyTarget:50000,reminderDay:1});check(r.data.items.find(x=>x.type==='preferences').amount===50000,'weekly plan persisted');check((await request('B')).data.rewards.length===0,'journey owner isolation');

// Update compatibility: no rewrites of pre-existing financial records.
const snapshot=(await request('A')).data.items;
r=await request('A',create({type:'card_cycle',cardId:card,month:'2026-11',closingDate:'2026-10-29',deadline:'2026-11-10'}));check(r.status===200,'actual invoice dates accepted');for(const row of snapshot)assert.deepEqual(r.data.items.find(x=>x.id===row.id),row);check(true,'invoice configuration preserves every existing record');
const cycle=r.data.items.find(x=>x.type==='card_cycle');check((await request('B',{action:'update',key:randomUUID(),id:cycle.id,record:{type:'card_cycle',cardId:card,month:'2026-11',closingDate:'2026-10-29',deadline:'2026-11-10'}})).status===400,'foreign invoice configuration blocked');
check((await request('A',create({type:'card_cycle',cardId:card,month:'2026-11',closingDate:'2026-10-29',deadline:'2026-11-10'}))).status===400,'duplicate cycle rejected');
const storedCard=snapshot.find(x=>x.id===card);r=await request('A',{action:'update',key:randomUUID(),id:card,record:{...storedCard,closing:31,due:7,dueRule:'business7',holidays:['2026-11-02']}});check(r.status===200,'existing card allows business day rule and closing 31');for(const row of snapshot.filter(x=>x.id!==card))assert.deepEqual(r.data.items.find(x=>x.id===row.id),row);check(true,'rule change preserves purchases payments and balances');
const installment=snapshot.find(x=>x.type==='purchase');r=await request('A',{action:'move_purchase',key:randomUUID(),id:installment.id,month:'2026-10'});check(r.data.items.find(x=>x.id===installment.id).amount===installment.amount&&r.data.items.find(x=>x.id===installment.id).month==='2026-10','explicit move preserves installment amount');check((await request('B',{action:'move_purchase',key:randomUUID(),id:installment.id,month:'2026-10'})).status===400,'foreign installment move blocked');
// Mission actions originate in regular forms, without progress controls.
r=await request('C',create({type:'card',name:'C',limit:10000,closing:30,due:7}));const cc=r.data.items[0].id;r=await request('C',create({type:'purchase',name:'Daily',amount:100,date:'2026-09-28',cardId:cc,category:'Compras',installments:1,month:'2026-10'}));check(r.data.rewards.some(x=>x.code==='habit_record'),'card purchase completes daily record mission');
r=await request('C',create({type:'budget',category:'Compras',amount:1000,month:'2026-09'}));check(r.data.rewards.some(x=>x.code==='habit_review_budget'),'regular budget form completes mission');r=await request('C',create({type:'investment',name:'Asset',quantity:'0',cost:0,value:0,category:'Investimentos'}));check(r.data.rewards.some(x=>x.code==='habit_review_investments'),'regular portfolio form completes review mission');r=await request('C',create({type:'goal',name:'Reserve',target:1000,current:100,deadline:'2027-01-01'}));check(r.data.rewards.some(x=>x.code==='habit_contribute'),'initial reserve completes goal mission');
const cSnapshot=r.data.items;await db.prepare('DELETE FROM journey_rewards WHERE user_id=?').bind('C').run();r=await request('C',{action:'sync_journey',key:randomUUID()});check(['habit_record','habit_review_budget','habit_review_investments','habit_contribute'].every(code=>r.data.rewards.some(x=>x.code===code)),'sync recovers missed missions from today');for(const row of cSnapshot)assert.deepEqual(r.data.items.find(x=>x.id===row.id),row);check(true,'mission recovery leaves financial records unchanged');const previousRewards=r.data.rewards.length;r=await request('C',{action:'sync_journey',key:randomUUID()});check(r.data.rewards.length===previousRewards,'mission synchronization caps rewards');

r=await request('D',create({type:'account',name:'Recurring account',initial:0}));const da=r.data.items[0].id;r=await request('D',create({type:'recurring',name:'Rent',amount:100,date:'2026-10-01',accountId:da,category:'Moradia',kind:'expense'}));check(r.data.rewards.some(x=>x.code==='habit_record')&&r.data.rewards.some(x=>x.code==='first_recurring'),'recurring setup earns XP before payment');const dSnapshot=r.data.items;await db.prepare('DELETE FROM journey_rewards WHERE user_id=?').bind('D').run();r=await request('D',{action:'sync_journey',key:randomUUID()});check(r.data.rewards.some(x=>x.code==='habit_record')&&r.data.rewards.some(x=>x.code==='first_recurring'),'existing recurrence XP recovered');for(const row of dSnapshot)assert.deepEqual(r.data.items.find(x=>x.id===row.id),row);check(true,'recurring reward recovery preserves all records');
// Recurrence end date, preservation and mission regression checks.
const recInput={type:'recurring',name:'Bounded rent',amount:100,date:'2026-07-31',endDate:'2026-09-30',accountId:da,category:'Moradia',kind:'expense'};
check((await request('D',create({...recInput,endDate:'2026-07-30'}))).status===400,'end before start rejected');
check((await request('D',create({...recInput,endDate:'2026-02-31'}))).status===400,'invalid end calendar date rejected');
r=await request('D',create(recInput));const bounded=r.data.items.find(x=>x.name==='Bounded rent');
check(bounded.endDate==='2026-09-30','end date persisted');
r=await request('D',{action:'confirm_recurring',key:randomUUID(),id:bounded.id,date:'2026-09-30'});check(r.status===200,'inclusive final occurrence accepted');
const preserved=r.data.items.filter(x=>x.id!==bounded.id),savedRewards=r.data.rewards;
r=await request('D',{action:'update',key:randomUUID(),id:bounded.id,record:{...recInput,endDate:'2026-08-31'}});check(r.status===200&&r.data.items.find(x=>x.id===bounded.id).endDate==='2026-08-31','edit retains recurrence id');
for(const row of preserved)assert.deepEqual(r.data.items.find(x=>x.id===row.id),row);for(const reward of savedRewards)assert.deepEqual(r.data.rewards.find(x=>x.key===reward.key),reward);check(true,'ending recurrence preserves historical transactions and rewards');
check((await request('D',{action:'confirm_recurring',key:randomUUID(),id:bounded.id,date:'2026-09-30'})).status===400,'after end rejected even when in past');
r=await request('D',{action:'update',key:randomUUID(),id:bounded.id,record:{...recInput,endDate:undefined}});check(r.status===200&&!r.data.items.find(x=>x.id===bounded.id).endDate,'end date can be removed');
check((await request('D',{action:'delete',key:randomUUID(),id:bounded.id})).status===400,'confirmed recurring rule cannot be orphaned');
const beforePublic=(await request('A')).data;
for(const path of ['/demo','/apresentacao']){const page=await mf.dispatchFetch('https://app.test'+path);check(page.status===200,'public route renders without identity '+path)}
assert.deepEqual((await request('A')).data,beforePublic);check(true,'public routes preserve private snapshot');
const rev=await db.prepare('SELECT revision FROM user_versions WHERE user_id=?').bind('A').first();let failed=false;try{await db.batch([db.prepare('INSERT INTO operations (id,user_id,key,digest,created_at,revision) VALUES (?,?,?,?,?,(SELECT revision FROM user_versions WHERE user_id=? AND revision=?))').bind(randomUUID(),'A',randomUUID(),'digest','now','A',rev.revision-1),db.prepare('DELETE FROM financial_records WHERE user_id=?').bind('A')])}catch{failed=true}check(failed,'stale revision aborts batch');check((await request('A')).data.items.length>0,'rollback preserves records');
const html=await mf.dispatchFetch('https://app.test/',{headers:{'oai-authenticated-user-id':'A','oai-authenticated-user-email':'A@example.test'}});const rendered=await html.text();check(html.status===200&&rendered.includes('Seu reino'),'authenticated page renders');
const manifest=JSON.parse(await readFile('public/manifest.webmanifest','utf8'));check(manifest.start_url==='/'&&manifest.display==='standalone','PWA manifest valid');const worker=await readFile('public/sw.js','utf8');check(worker.includes("url.pathname.startsWith('/api/')"),'service worker excludes financial API');console.log(`${checks} integration checks passed`);
}finally{await mf.dispose()}
