import test from 'node:test';import assert from 'node:assert/strict';
import {rewardsFor,progress} from '../.sites-runtime/test-build/journey.js';
import {parseImport} from '../.sites-runtime/test-build/import.js';
import {quantityUnits,quantityText,positionValue,simulateGoal,totals,forecast} from '../.sites-runtime/test-build/finance.js';
import {answerQuestion} from '../.sites-runtime/test-build/assistant.js';
test('CSV handles quoted descriptions, Brazilian decimals and stable external IDs',()=>{const rows=parseImport('data;descricao;valor;categoria;id\n30/09/2026;"Café; almoço";-1.234,56;Alimentação;id-1\n2026-09-30;Salário;5000,00;Salário;id-2','csv');assert.equal(rows[0].amount,123456);assert.equal(rows[0].kind,'expense');assert.equal(rows[0].name,'Café; almoço');assert.equal(rows[0].externalId,'id-1');assert.equal(rows[1].amount,500000)});
test('OFX SGML and XML normalize date/amount/ID',()=>{const rows=parseImport('<OFX><BANKTRANLIST><STMTTRN><DTPOSTED>20260930120000[-4:GMT]<TRNAMT>-29.99<FITID>abc<MEMO>Mercado</STMTTRN></BANKTRANLIST></OFX>','ofx');assert.deepEqual(rows[0],{externalId:'abc',name:'Mercado',date:'2026-09-30',amount:2999,kind:'expense',category:'Outros'})});
test('CSV invalid dates and missing headers fail before import',()=>{assert.throws(()=>parseImport('data;descricao;valor\n2026-02-31;X;1','csv'));assert.throws(()=>parseImport('nome;dinheiro\nX;1','csv'))});
test('import row limit is enforced',()=>{assert.throws(()=>parseImport('data;descricao;valor\n'+Array.from({length:201},()=> '2026-09-30;X;1').join('\n'),'csv'))});
test('decimal investment quantities preserve exact units',()=>{assert.equal(quantityUnits('0.00000001'),1n);assert.equal(quantityText(quantityUnits('0.1')+quantityUnits('0.2')),'0.3');assert.equal(positionValue('0.3',10001),3000);assert.throws(()=>quantityUnits('1.000000001'))});
test('savings rate excludes investment purchases and planned card payments do not reduce liability',()=>{const items=[{id:'a',type:'account',initial:10000},{id:'i',type:'transaction',accountId:'a',kind:'investment_buy',amount:1000,status:'posted',date:'2026-09-30'},{id:'p',type:'purchase',amount:5000,month:'2026-10'},{id:'f',type:'transaction',kind:'card_payment',accountId:'a',amount:5000,status:'planned',date:'2026-10-05'}];assert.equal(totals(items,'2026-09').expenses,0);assert.equal(totals(items,'2026-09').cards,5000);assert.equal(totals(items,'2026-09').balance,9000)});
test('rewards are capped once per day and not based on monetary size',()=>{const small=[{id:'t',type:'transaction',status:'posted',amount:1}];const big=[{...small[0],amount:100000000}];const a=rewardsFor('create',small,[],'2026-09-30','transaction');assert.deepEqual(a,rewardsFor('create',big,[],'2026-09-30','transaction'));assert.equal(rewardsFor('create',small,a,'2026-09-30','transaction').length,0)});
test('buying investments alone does not grant habit XP',()=>{assert.deepEqual(rewardsFor('trade',[{id:'i',type:'investment',value:10000}],[],'2026-09-30'),[])});
test('constancy achievements depend on distinct dates',()=>{const prior=['2026-09-28','2026-09-29'].map(date=>({key:'habit_record:'+date,code:'habit_record',title:'x',xp:5,date}));const next=rewardsFor('create',[{id:'t',type:'transaction',status:'posted'}],prior,'2026-09-30','transaction');assert.ok(next.some(x=>x.code==='three_days'));assert.equal(progress([...prior,...next],[],'2026-09-30').streak,3)});
test('world stages require real achievement and activity milestones',()=>{assert.equal(progress([],[],'2026-09-30').stage,0);const rewards=['first_record','first_goal'].map(code=>({key:'achievement:'+code,code,title:'x',xp:20,date:'2026-09-30'}));assert.equal(progress(rewards,[],'2026-09-30').stage,1)});
test('goal simulation never promises returns and handles zero contributions',()=>{assert.equal(simulateGoal({target:100000,current:25000},0),null);assert.equal(simulateGoal({target:100000,current:25000},10000).months,8)});
test('local assistant answers only registered food expenses',()=>{const result=answerQuestion('Quanto gastei com alimentação?',[{id:'t',type:'transaction',kind:'expense',status:'posted',category:'Alimentação',date:'2026-09-30',amount:1234}],'2026-09');assert.ok(result.answer.includes('12,34'));assert.ok(result.evidence.includes('2026-09'))});
test('old recurring rules project current anchored occurrences',()=>{const points=forecast([{id:'a',type:'account',initial:10000},{id:'r',type:'recurring',date:'2000-01-31',kind:'expense',amount:100}],35,'2026-09-30');assert.equal(points.at(-1).balance,9800)});

test('normal screens complete daily missions with capped XP',()=>{for(const [kind,code] of [['purchase','habit_record'],['budget','habit_review_budget'],['investment','habit_review_investments'],['contribution','habit_contribute']]){const rewards=rewardsFor('create',[],[],'2026-09-30',kind);assert.ok(rewards.some(r=>r.code===code));assert.equal(rewardsFor('update',[],rewards,'2026-09-30',kind).filter(r=>r.code===code).length,0)}});
test('actual invoice dates override estimates without moving stored purchases',async()=>{const {invoiceDue,invoiceAmounts,businessDay,purchaseMonth,calendarDay}=await import('../.sites-runtime/test-build/finance.js');const card={id:'c',type:'card',closing:30,due:7,dueRule:'business7',holidays:['2026-10-12']};assert.equal(businessDay('2026-10',7,card.holidays),'2026-10-09');assert.equal(businessDay('2026-09',7,['2026-09-07']),'2026-09-10');assert.equal(calendarDay('2027-02',31),'2027-02-28');const purchase={id:'p',type:'purchase',cardId:'c',amount:100,month:'2026-10'};const cycle={id:'f',type:'card_cycle',cardId:'c',month:'2026-10',closingDate:'2026-09-29',deadline:'2026-10-13'};const items=[card,purchase,cycle];assert.equal(invoiceDue(items,card,'2026-10'),'2026-10-13');assert.equal(invoiceAmounts(items)[0].date,'2026-10-13');assert.equal(purchase.month,'2026-10');assert.equal(purchaseMonth(items,card,'2026-09-28'),'2026-10');assert.equal(purchaseMonth(items,card,'2026-06-01'),'2026-07')});

test('recurring setup grants achievement and daily organization XP once',()=>{const items=[{id:'r',type:'recurring',amount:100}];const first=rewardsFor('create',items,[],'2026-09-30','recurring');assert.ok(first.some(r=>r.code==='first_recurring'&&r.xp===20));assert.ok(first.some(r=>r.code==='habit_record'&&r.xp===5));assert.equal(rewardsFor('create',[...items,{id:'r2',type:'recurring'}],first,'2026-09-30','recurring').length,0);const recovered=rewardsFor('sync_journey',items,[],'2026-09-30');assert.ok(recovered.some(r=>r.code==='first_recurring'));assert.ok(!recovered.some(r=>r.code==='habit_record'))});
