import {env} from 'cloudflare:workers';
import type {Reward} from '../domain/journey';
import type {Entity} from '../domain/finance';
export function database(){if(!env.DB)throw new Error('Armazenamento indisponível. Tente novamente mais tarde.');return env.DB}
export async function readRecords(userId:string):Promise<Entity[]>{const {results}=await database().prepare('SELECT id,type,data FROM financial_records WHERE user_id = ? ORDER BY created_at DESC').bind(userId).all<{id:string;type:string;data:string}>();return results.map(r=>({...JSON.parse(r.data),id:r.id,type:r.type}))}
export async function commit(userId:string,key:string,digest:string,revision:number,add:Entity[],remove:string[]=[],clear=false,rewards:Reward[]=[]){const db=database();const existing=await db.prepare('SELECT digest FROM operations WHERE user_id=? AND key=?').bind(userId,key).first<{digest:string}>();if(existing){if(existing.digest!==digest)throw new Error('Identificador reutilizado para outra operação.');return}const now=new Date().toISOString();const batch=[db.prepare('INSERT OR IGNORE INTO user_versions (user_id,revision) VALUES (?,0)').bind(userId),db.prepare('INSERT INTO operations (id,user_id,key,digest,created_at,revision) VALUES (?,?,?,?,?,(SELECT revision FROM user_versions WHERE user_id=? AND revision=?))').bind(crypto.randomUUID(),userId,key,digest,now,userId,revision),db.prepare('UPDATE user_versions SET revision=revision+1 WHERE user_id=?').bind(userId)];if(clear){batch.push(db.prepare('DELETE FROM financial_records WHERE user_id=?').bind(userId));batch.push(db.prepare('DELETE FROM journey_rewards WHERE user_id=?').bind(userId))}for(const id of remove)batch.push(db.prepare('DELETE FROM financial_records WHERE user_id=? AND id=?').bind(userId,id));for(const row of add)batch.push(db.prepare('INSERT INTO financial_records (id,user_id,type,data,created_at) VALUES (?,?,?,?,?)').bind(row.id,userId,row.type,JSON.stringify(row),now));for(const reward of rewards)batch.push(db.prepare('INSERT INTO journey_rewards (id,user_id,event_key,code,title,xp,date,created_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(user_id,event_key) DO NOTHING').bind(crypto.randomUUID(),userId,reward.key,reward.code,reward.title,reward.xp,reward.date,now));batch.push(db.prepare('INSERT INTO audit_events (id,user_id,event,created_at) VALUES (?,?,?,?)').bind(crypto.randomUUID(),userId,clear?'DATA_CLEARED':add.length?'RECORDS_CREATED':'RECORD_DELETED',now));await db.batch(batch)}

export async function getRevision(userId:string){const row=await database().prepare('SELECT revision FROM user_versions WHERE user_id=?').bind(userId).first<{revision:number}>();return row?.revision||0}
export async function alreadyCommitted(userId:string,key:string,digest:string){const row=await database().prepare('SELECT digest FROM operations WHERE user_id=? AND key=?').bind(userId,key).first<{digest:string}>();if(row&&row.digest!==digest)throw new Error('Identificador reutilizado para outra operação.');return !!row}

export async function readRewards(userId:string):Promise<Reward[]>{const {results}=await database().prepare('SELECT event_key as key,code,title,xp,date FROM journey_rewards WHERE user_id=? ORDER BY created_at ASC').bind(userId).all<Reward>();return results}

export async function activityKinds(userId:string,date:string){const {results}=await database().prepare('SELECT type,data,created_at FROM financial_records WHERE user_id=? AND created_at>=?').bind(userId,date+'T00:00:00Z').all<{type:string;data:string;created_at:string}>();return [...new Set(results.filter(r=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Cuiaba',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(r.created_at))===date).flatMap(r=>{const x=JSON.parse(r.data) as Entity;if(r.type==='transaction'&&x.status==='posted')return ['transaction'];if(r.type==='purchase')return ['purchase'];if(r.type==='recurring')return ['recurring'];if(r.type==='budget'&&x.month===date.slice(0,7))return ['budget'];if(r.type==='investment')return ['investment'];if(r.type==='contribution'&&x.kind==='contribution')return ['contribution'];return []}))]}
